version: '3.9'

services:
  postgres:
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ipfs
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
 
  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - 9090:8080
